"""Rendering the gate's verdict for a human, and the checklist only a human can finish.

Two audiences. `render_gate_table` is read once, on a terminal, by whoever ran ingestion.
`render_section_starts` is ADR-0007's committed one-time hand-verification artifact: it
prints the first lines of every extracted Section so a person can confirm the extractor
landed on the real section rather than a table-of-contents row.

The gate cannot make that judgement — it can only prove the text is long, wordy, and
bounded, all of which a plausible mis-extraction also is. The checklist ships unticked on
purpose.
"""

from __future__ import annotations

from collections.abc import Sequence

from finbrief.ingestion.gate import GateFinding, form_family, incorporated_sections
from finbrief.ingestion.model import ExtractedFiling, Section

#: How much of each Section's opening to show. Enough to recognise the heading and the
#: first sentence under it — which is exactly the evidence that distinguishes the real
#: section from a TOC row, and no more, since fifteen companies x four Sections is already
#: sixty judgements to make by hand.
SECTION_START_CHARS = 320


def render_gate_table(
    filings: Sequence[ExtractedFiling], findings: Sequence[GateFinding]
) -> str:
    """A company x Section grid of character counts, with failures called out beneath."""
    failed = {(f.ticker, f.section) for f in findings}
    header = f"{'':<7}{'':<9}" + "".join(f"{s.value:>12}" for s in Section)
    lines = [
        "Section-detection gate (ADR-0007) — characters extracted per Section",
        header,
        "-" * len(header),
    ]

    for filing in filings:
        ticker = filing.ref.ticker
        referenced = incorporated_sections(filing)
        cells = []
        for section in Section:
            text = filing.sections.get(section)
            if section in referenced:
                cell = "->Item 7"
            elif text:
                cell = f"{len(text):,}" + ("FAIL" if (ticker, section) in failed else "")
            else:
                cell = "-" + ("FAIL" if (ticker, section) in failed else "")
            cells.append(f"{cell:>12}")
        # `form_family`, not a second startswith: this column has to agree with the
        # finding list below it, and two implementations of "is this a 10-K" is how
        # a table ends up contradicting the gate that produced it.
        annual = "" if form_family(filing.latest_annual_form) == "10-K" else " !ANNUAL"
        lines.append(
            f"{ticker:<7}{'FY' + str(filing.ref.fiscal_year):<9}" + "".join(cells) + annual
        )

    referenced_total = sum(len(incorporated_sections(f)) for f in filings)
    lines.append("")
    if referenced_total:
        lines.append(
            f"{referenced_total} Section(s) incorporated by reference into Item 7 — "
            f"lawful, not ingested, listed in the verification artifact (ADR-0007)."
        )
    if findings:
        lines.append(f"{len(findings)} finding(s):")
        lines.extend(f"  - {finding}" for finding in findings)
    else:
        lines.append(f"All {len(filings) * len(Section)} company x Section checks passed.")

    return "\n".join(lines)


def render_section_starts(filings: Sequence[ExtractedFiling]) -> str:
    """The hand-verification checklist of extracted Section starts (ADR-0007).

    Emitted with every box unticked. Ticking them is a human reading each excerpt against
    the filing on EDGAR — the whole value of the artifact is that a person, not the
    extractor, confirmed the extractor.
    """
    lines = [
        "# Hand-verification: extracted Section starts",
        "",
        "One-time verification artifact required by ADR-0007. The section-detection gate",
        "proves each Section is present, non-empty, length-bounded, body-heavy, and free",
        "of the next Item's content — none of which distinguishes the real Item 1A from a",
        "plausible mis-extraction that is also all five. Only reading the text does, which",
        "is why these boxes ship unticked.",
        "",
        "**How to verify.** For each row, open the filing at the linked EDGAR URL, find",
        "the Item, and confirm the excerpt below is where that Item actually begins — not",
        "a table-of-contents row, not the tail of the previous Item, not a part summary.",
        "Tick the box when you have checked it against the source.",
        "",
        "Rows marked **incorporated by reference** are Sections the filer answered with a",
        "pointer to Item 7 rather than with text. They are deliberately not ingested — a",
        "pointer grounds nothing — and the content they point at is in the knowledge base",
        "under `Item 7`. Verify that the filing really does hand the Item off, rather than",
        "the extractor having landed on a stub.",
        "",
        f"Generated by `scripts/ingest_filings.py --section-starts`. {len(filings)} "
        f"filing(s), {len(filings) * len(Section)} Sections to verify.",
        "",
    ]

    for filing in filings:
        ref = filing.ref
        lines += [
            f"## {ref.ticker} — FY{ref.fiscal_year} {ref.form}",
            "",
            f"- Accession: `{ref.accession}`  ·  filed {ref.filing_date}",
            f"- EDGAR: {ref.url or '(no URL recorded)'}",
            "",
        ]
        referenced = incorporated_sections(filing)
        for section in Section:
            text = filing.sections.get(section)
            lines.append(f"### {section.value}. {section.heading}")
            lines.append("")
            if not text:
                lines.append(
                    "- [ ] **NOT EXTRACTED** — nothing to verify; the gate failed this."
                )
                lines.append("")
                continue
            if section in referenced:
                lines.append(
                    "- [ ] Verified **incorporated by reference — not ingested**. Confirm "
                    "the filing really does hand this Item off to Item 7 (which *is* "
                    "ingested), rather than the extractor having found a stub."
                )
                lines.append("")
                lines.append("```text")
                lines.append(_excerpt(text))
                lines.append("```")
                lines.append("")
                continue
            lines.append(f"- [ ] Verified — {len(text):,} characters extracted")
            lines.append("")
            lines.append("```text")
            lines.append(_excerpt(text))
            lines.append("```")
            lines.append("")

    return "\n".join(lines)


def _excerpt(text: str) -> str:
    """The Section's opening, cut at a word boundary."""
    if len(text) <= SECTION_START_CHARS:
        return text
    head = text[:SECTION_START_CHARS]
    return head[: head.rfind(" ")] + " …"
