"""The machine evidence a run leaves behind: the gate table and the ingest report.

`docs/verification/ingest-report.md` is regenerated by every `scripts/ingest_filings.py`
run, so "all Universe companies ingest" (issue #3) is checkable from the repo — the gate
table and per-company chunk counts are committed evidence, not a comment's say-so. The
renderer is pure; the script feeds it what the run and the store report.
"""

import re

from finbrief.ingestion.gate import check_filing
from finbrief.ingestion.model import ExtractedFiling, FilingRef, Section
from finbrief.ingestion.reporting import render_gate_table, render_ingest_report

BODY = "The Company designs and sells devices to customers worldwide. " * 40


def a_filing(ticker="AAPL", accession="0000320193-25-000079", *, sections=None, form="10-K"):
    return ExtractedFiling(
        ref=FilingRef(
            ticker=ticker,
            form=form,
            accession=accession,
            fiscal_year=2025,
            filing_date="2025-10-31",
        ),
        latest_annual_form=form,
        sections=sections
        if sections is not None
        else {s: f"{s.value}. {s.heading}\n\n{BODY}" for s in Section},
    )


# --- The gate table -----------------------------------------------------------------


def test_the_gate_table_separates_the_count_from_the_fail_marker():
    # "394,858FAIL" reads as one token. The marker needs a separator, in the counted cell
    # and in the not-extracted cell alike.
    sections = {s: f"{s.value}. {s.heading}\n\n{BODY}" for s in Section}
    sections[Section.RISK_FACTORS] = "Item 1A. Risk Factors" + "." * 4000 + " 12"
    del sections[Section.MARKET_RISK]
    filing = a_filing(sections=sections)
    findings = check_filing(filing)
    assert len(findings) == 2, "the fixture must fail one counted and one missing Section"

    table = render_gate_table([filing], findings)

    assert not re.search(r"[\d,-]FAIL", table)
    assert table.count(" FAIL") == 2


def test_a_referenced_section_renders_as_a_pointer_cell_not_a_count():
    # The cell has to say where the content went, not pretend a character count is a
    # Section — "JPM has no Item 7A chunks" is a fact a reader of the table needs.
    sections = {s: f"{s.value}. {s.heading}\n\n{BODY}" for s in Section}
    sections[Section.MARKET_RISK] = (
        "Item 7A. Quantitative and Qualitative Disclosures About Market Risk\n\n"
        "Refer to the Market Risk Management section of Management's discussion and "
        "analysis on pages 133-142."
    )
    filing = a_filing("JPM", sections=sections)

    table = render_gate_table([filing], [])

    assert "->Item 7" in table
    assert "incorporated by reference" in table


def test_a_non_10k_filer_is_flagged_on_its_row():
    filing = a_filing("SAP", form="20-F", sections={})

    table = render_gate_table([filing], check_filing(filing))

    assert "!ANNUAL" in table


# --- The ingest report ----------------------------------------------------------------


def test_a_passing_run_reports_per_company_counts_and_the_total():
    filings = [a_filing("AAPL"), a_filing("MSFT", "0000789019-25-000118")]

    report = render_ingest_report(
        filings,
        [],
        generated="2026-07-26 12:00 UTC",
        store_counts={"AAPL": 152, "MSFT": 237},
        written={"MSFT": 237},
        skipped=("AAPL",),
    )

    assert "GATE PASSED" in report
    assert "characters extracted per Section" in report, "the gate table is embedded"
    assert "152" in report and "237" in report
    assert "389" in report, "the total is summed from the store, not asserted"
    assert "0000320193-25-000079" in report, "each row pins its accession"
    assert "skipped" in report, "an idempotent re-run says so instead of claiming writes"
    assert "2026-07-26 12:00 UTC" in report


def test_a_ticker_in_the_store_but_absent_from_the_run_still_gets_a_row():
    # A --tickers run fetches one company, but the report attests to the whole
    # collection: what it holds for companies the run never touched must not vanish.
    report = render_ingest_report(
        [a_filing("AAPL")],
        [],
        generated="2026-07-26 12:00 UTC",
        store_counts={"AAPL": 152, "NVDA": 296},
        written={"AAPL": 152},
    )

    nvda_row = next(line for line in report.splitlines() if line.startswith("| NVDA"))
    assert "296" in nvda_row
    assert nvda_row.count("—") == 3, "no fiscal year, accession, or action to claim"


def test_a_dry_run_reports_the_gate_and_says_no_store_was_consulted():
    report = render_ingest_report(
        [a_filing()],
        [],
        generated="2026-07-26 12:00 UTC",
        store_counts=None,
    )

    assert "GATE PASSED" in report
    assert "dry run" in report.lower()
    assert "## Chunks in the collection" not in report, "no store was consulted"


def test_a_failed_run_reports_the_findings_and_that_nothing_was_written():
    sections = {s: f"{s.value}. {s.heading}\n\n{BODY}" for s in Section}
    del sections[Section.MDA]
    filing = a_filing(sections=sections)
    findings = check_filing(filing)

    report = render_ingest_report(
        [filing],
        findings,
        generated="2026-07-26 12:00 UTC",
        store_counts=None,
    )

    assert "GATE FAILED" in report
    assert "section_found" in report, "the findings travel with the evidence"
    assert "nothing was written" in report.lower()
